import { tableSchema } from '@nozbe/watermelondb';

const pedidoSchema = tableSchema({
    name:'pedido',
    columns: [
        {
            name:'pedido_id',
            type:'string'
        },
        {
            name:'CODIGO_RETAGUARDA',
            type:'string'
        },
        {
            name:'data_pedido',
            type:'string'
        },
        {
            name:'codigo_cliente',
            type:"string"
        },
        {
            name:'data_entrega',
            type:'string'
        },
        {
            name:'hora_pedido',
            type:'string'
        },
        {
            name:'codigo_usuario',
            type:'string'
        },
        {
            name:'codigo_vendedor',
            type:'string'
        },
        {
            name:'status',
            type:'string'
        },
        {
            name:'prazo1',
            type:'string'
        },
        {
            name:'prazo2',
            type:'string'
        },
        {
            name:"prazo3",
            type:'string'
        },
        {
            name:'prazo4',
            type:'string'
        },
        {
            name:'prazo5',
            type:'string'
        },
        {
            name:'obs',
            type:'string'
        },
        {
            name:'valor_desconto',
            type:"string"
        },
        {
            name:'id_tabela_preco',
            type:'string'
        },
        {
            name:'retirada',
            type:'string'
        },
        {
            name:'cnpj_emp',
            type:'string'
        }
    ]
});

export {pedidoSchema}